USE XYZ
DELIMITER //

CREATE PROCEDURE GetWatchHistoryBySubscriber(IN sub_id INT)
BEGIN 
DECLARE SHOW_TITLE VARCHAR(100); 
DECLARE WATCH_TIME INT;
DECLARE FIN BOOL DEFAULT FALSE;

DECLARE WATCH_CURSOR CURSOR FOR 
SELECT S.Title, W.WatchTime
FROM WatchHistory W
JOIN Shows S ON W.ShowID = S.ShowID
WHERE W.SubscriberID = sub_id;

DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIN = TRUE; 

DROP TEMPORARY TABLE IF EXISTS TempWatchHistory;
CREATE TEMPORARY TABLE TempWatchHistory (
ShowTitle VARCHAR(100),
WatchTime INT);

OPEN WATCH_CURSOR; 

WATCH_LOOP: LOOP 
FETCH WATCH_CURSOR INTO SHOW_TITLE, WATCH_TIME; 
IF FIN = TRUE THEN 
LEAVE WATCH_LOOP; 
END IF; 
INSERT INTO TempWatchHistory VALUES (SHOW_TITLE, WATCH_TIME);
END LOOP WATCH_LOOP; 

CLOSE WATCH_CURSOR; 

SELECT * FROM TempWatchHistory;
DROP TEMPORARY TABLE IF EXISTS TempWatchHistory;
END //

DELIMITER ;


CALL GetWatchHistoryBySubscriber(1);
