USE xyz;
DELIMITER //

CREATE PROCEDURE SendWatchTimeReport()
BEGIN
DECLARE SUB_ID INT;
DECLARE FINISHED INT DEFAULT 0;

DECLARE SUB_CURSOR CURSOR FOR
SELECT DISTINCT s.SubscriberID
FROM Subscribers s
JOIN WatchHistory w ON s.SubscriberID = w.SubscriberID;

DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;

DROP TEMPORARY TABLE IF EXISTS TEMP_REPORT;
CREATE TEMPORARY TABLE TEMP_REPORT (
SUBSCRIBER_ID INT,
SHOW_TITLE VARCHAR(100),
WATCH_TIME INT);

OPEN SUB_CURSOR;

SUB_LOOP: LOOP
FETCH SUB_CURSOR INTO SUB_ID;
IF FINISHED = 1 THEN
LEAVE SUB_LOOP;
END IF;

INSERT INTO TEMP_REPORT (SUBSCRIBER_ID, SHOW_TITLE, WATCH_TIME)
SELECT SUB_ID, S.Title, W.WatchTime
FROM WatchHistory W
JOIN Shows S ON W.ShowID = S.ShowID
WHERE W.SubscriberID = SUB_ID;
END LOOP SUB_LOOP;

CLOSE SUB_CURSOR;

SELECT * FROM TEMP_REPORT;

DROP TEMPORARY TABLE IF EXISTS TEMP_REPORT;
END //

DELIMITER ;

CALL SendWatchTimeReport();
