USE xyz;
DELIMITER //

CREATE PROCEDURE PrintAllSubscribersWatchHistory()
BEGIN
DECLARE SUB_ID INT;
DECLARE FINISHED INT DEFAULT 0;

DECLARE SUB_CURSOR CURSOR FOR
SELECT SubscriberID FROM Subscribers;

DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;

DROP TEMPORARY TABLE IF EXISTS TEMP_WATCH_HISTORY;
CREATE TEMPORARY TABLE TEMP_WATCH_HISTORY (
SubscriberID INT,
ShowTitle VARCHAR(100),
WatchTime INT);

OPEN SUB_CURSOR;

SUB_LOOP: LOOP
FETCH SUB_CURSOR INTO SUB_ID;
IF FINISHED = 1 THEN
LEAVE SUB_LOOP;
END IF;

INSERT INTO TEMP_WATCH_HISTORY (SubscriberID, ShowTitle, WatchTime)
SELECT SUB_ID, S.Title, W.WatchTime
FROM WatchHistory W
JOIN Shows S ON W.ShowID = S.ShowID
WHERE W.SubscriberID = SUB_ID;
END LOOP SUB_LOOP;

CLOSE SUB_CURSOR;

SELECT * FROM TEMP_WATCH_HISTORY;

DROP TEMPORARY TABLE IF EXISTS TEMP_WATCH_HISTORY;
END //

DELIMITER ;

CALL PrintAllSubscribersWatchHistory();
